project:
  type: website
  output-dir: docs

publish:
  gh-pages: true

website:
  title: "Michael Helm's Portfolio"
  search: true  # Enable search functionality
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "About ME.qmd"
        text: "About Me"
      - href: resume.qmd
        text: "Resume"  # Links to the embedded resume page
      - href: ml-combine-project.qmd
        text: "Machine Learning Project"  # Links to the embedded project page
      - href: internship.qmd
        text: "Internship Experience"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


