project:
  type: website
  output-dir: docs
  
publish:
  gh-pages: true

website:
  title: "PSTAT 199 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

