project:
  type: website
  output-dir: docs

publish:
  gh-pages: true

website:
  title: "Michael Helm's Portfolio"
  search: true  # Enable search functionality
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About Me"
      - href: "Michael Helm Resume F24 DS.pdf"
        text: "Resume"
      - href: "NFL Combine Final Project (Classification).pdf"
        text: "NFL Combine Project"
      - href: internship.qmd
        text: "Internship"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


